import { AnalysisResult } from '@/types/bio';

export const downloadFile = (content: string, filename: string, mimeType: string) => {
    // Sanitize filename to prevent OS errors
    const safeFilename = filename.replace(/[^a-z0-9.-]/gi, '_');
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = safeFilename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};

export const exportAsFASTA = (result: AnalysisResult): string => {
    const header = `>${result.name} | ${result.type} | Length: ${result.length}bp | BioSeq Portal`;
    const sequence = result.sequence.match(/.{1,80}/g)?.join('\n') || result.sequence;
    return `${header}\n${sequence}`;
};

export const exportAsGenBank = (result: AnalysisResult): string => {
    const now = new Date();
    const date = now.toISOString().slice(0, 10).replace(/-/g, '');
    const lines = [
        'LOCUS       ' + result.name.padEnd(16) + `${result.length} bp    DNA     linear   ${date}`,
        'DEFINITION  ' + `${result.type} sequence from BioSeq Portal analysis`,
        'ACCESSION   ' + result.id.toUpperCase(),
        'KEYWORDS    .',
        'SOURCE      BioSeq Portal',
        '  ORGANISM  synthetic construct',
        'REFERENCE   1  (bases 1 to ' + result.length + ')',
        '  AUTHORS   BioSeq Portal User',
        '  TITLE     Direct Submission',
        'FEATURES            Location/Qualifiers',
        '     source          1..' + result.length,
        '                     /organism="synthetic"',
        '                     /mol_type="genomic ' + (result.type === 'Protein' ? 'protein' : 'DNA') + '"',
    ];

    // Add restriction sites as features if available
    if (result.restrictionSites && result.restrictionSites.length > 0) {
        result.restrictionSites.forEach(site => {
            lines.push(`     misc_feature    ${site.position}..${site.position + site.sequence.length - 1}`);
            lines.push(`                     /note="${site.enzyme} restriction site"`);
        });
    }

    lines.push('ORIGIN');

    // Format sequence in GenBank format (60 chars per line)
    const seq = result.sequence.toUpperCase();
    let pos = 1;
    for (let i = 0; i < seq.length; i += 60) {
        const chunk = seq.substring(i, i + 60);
        const formatted = chunk.match(/.{1,10}/g)?.join(' ') || chunk;
        lines.push(`${pos.toString().padStart(9, ' ')}  ${formatted}`);
        pos += 60;
    }

    lines.push('//');
    return lines.join('\n');
};

export const exportAsCSV = (result: AnalysisResult): string => {
    const rows = [
        'Field,Value,Unit',
        `Sequence Name,${result.name}`,
        `Sequence Type,${result.type}`,
        `Length,${result.length},bp`,
        result.gcContent !== undefined ? `GC Content,${result.gcContent},%` : null,
        `Molecular Weight,${result.molecularWeight.toFixed(2)},Da`,
        `Analysis ID,${result.id}`,
        `Timestamp,${result.timestamp}`,
    ];

    // Add restriction sites
    if (result.restrictionSites && result.restrictionSites.length > 0) {
        rows.push('');
        rows.push('Restriction Sites');
        rows.push('Enzyme,Position,Sequence');
        result.restrictionSites.forEach(site => {
            rows.push(`${site.enzyme},${site.position},${site.sequence}`);
        });
    }

    // Add translation if available
    if (result.translation) {
        rows.push('');
        rows.push(`Translation (${result.type === 'DNA' ? 'DNA' : 'N/A'}),${result.translation}`);
    }

    return rows.filter(Boolean).join('\n');
};

export const exportAsJSON = (result: AnalysisResult): string => {
    return JSON.stringify(result, null, 2);
};

export const shareViaEmail = (result: AnalysisResult) => {
    const subject = encodeURIComponent(`BioSeq Portal Analysis: ${result.name}`);
    const body = encodeURIComponent(
        `Analysis Results for ${result.name}\n` +
        `Type: ${result.type}\n` +
        `Length: ${result.length}bp\n` +
        `GC Content: ${result.gcContent || 'N/A'}%\n` +
        `Molecular Weight: ${result.molecularWeight.toFixed(2)} Da\n\n` +
        `Generated by BioSeq Portal`
    );
    window.open(`mailto:?subject=${subject}&body=${body}`);
};

export const shareViaWhatsApp = (result: AnalysisResult) => {
    const text = encodeURIComponent(
        `*BioSeq Portal Analysis*\n\n` +
        `*Name:* ${result.name}\n` +
        `*Type:* ${result.type}\n` +
        `*Length:* ${result.length}bp\n` +
        `*GC Content:* ${result.gcContent || 'N/A'}%\n\n` +
        `Generated with BioSeq Portal`
    );
    window.open(`https://wa.me/?text=${text}`, '_blank');
};

export const copyToClipboard = async (text: string) => {
    await navigator.clipboard.writeText(text);
};

export const getShareText = (result: AnalysisResult): string => {
    return `BioSeq Portal Analysis: ${result.name} (${result.type}, ${result.length}bp)`;
};