import { AnalysisResult } from '@/types/bio';

/**
 * Generate a PyMOL script (.pml) for visualizing the structure
 * This creates a script that users can run in PyMOL desktop
 */
export const generatePyMOLScript = (result: AnalysisResult): string => {
    const pdbId = result.pdbId || '1hbb';
    const scriptName = result.name.replace(/[^a-zA-Z0-9]/g, '_');

    return `# PyMOL Script for ${result.name}
# Generated by BioSeq Portal
# PyMOL Version: 2.x or higher

# Load the structure
fetch ${pdbId}, async=0

# Set up the visualization
cmd.bg_color('white')
cmd.set('cartoon_fancy_helices', 1)
cmd.set('cartoon_highlight_color', 'grey50')
cmd.set('ray_trace_mode', 1)
cmd.set('antialias', 2)

# Create a nice representation
cmd.show('cartoon')
cmd.color('teal', 'chain A')
cmd.color('orange', 'chain B')

# Add surface if protein is small enough
if cmd.count_atoms() < 50000:
    cmd.show('surface', 'chain A')
    cmd.set('transparency', 0.5, 'surface')

# Label the structure
cmd.label('name CA and chain A', '"%s%s" % (resn, resi)')
cmd.set('label_font_id', 7)
cmd.set('label_size', -0.5)

# Set up the view
cmd.zoom('complete', 5)

# Ray trace and save high-quality image (optional - uncomment to use)
# cmd.ray(2400, 2400)
# cmd.png('${scriptName}_structure.png', dpi=300)

print("PyMOL session loaded successfully for ${result.name}")
print("PDB ID: ${pdbId}")
print("Analysis ID: ${result.id}")
`;
};

/**
 * Generate a PyMOL session file content
 * This creates a Python script that can recreate the analysis
 */
export const generatePyMOLSession = (result: AnalysisResult): string => {
    const pdbId = result.pdbId || '1hbb';

    return `# BioSeq Portal - PyMOL Session Export
# Analysis: ${result.name}
# PDB ID: ${pdbId}
# Sequence Type: ${result.type}

from pymol import cmd
import json

# Analysis metadata
analysis_data = ${JSON.stringify({
        name: result.name,
        id: result.id,
        type: result.type,
        length: result.length,
        pdbId: pdbId,
        timestamp: result.timestamp,
        gcContent: result.gcContent,
        molecularWeight: result.molecularWeight
    }, null, 4)}

# Save analysis data as PyMOL object
for key, value in analysis_data.items():
    cmd.set(f'bioseq_{key}', str(value))

# Load structure
cmd.fetch('${pdbId}')

# Apply standard visualization
cmd.show('cartoon')
cmd.color('spectrum')
cmd.bg_color('white')
`;
};

/**
 * Generate a PyMOL color script based on sequence properties
 * For example, color by GC content or conservation
 */
export const generatePyMOLColorScript = (result: AnalysisResult): string => {
    const pdbId = result.pdbId || '1hbb';

    return `# PyMOL Coloring Script for ${result.name}
# Colors structure based on sequence properties

fetch ${pdbId}, async=0

# Clear previous representations
cmd.hide('everything')

# Show cartoon representation
cmd.show('cartoon')

# Apply color scheme based on GC content
# Higher GC content areas are colored in warmer tones
fetch ${pdbId}, async=0

cmd.select('high_gc', 'resi 1-100')  # Placeholder selection
cmd.select('low_gc', 'resi 101-200')

cmd.color('red', 'high_gc')
cmd.color('blue', 'low_gc')

# Add labels for key residues
cmd.label('resn HIS+ARG+LYS and name CA', 'resn')
cmd.set('label_color', 'black')

# Final view setup
cmd.zoom('visible')
cmd.orient()
`;
};

/**
 * Download PyMOL script as .pml file
 */
export const downloadPyMOLScript = (result: AnalysisResult): void => {
    const content = generatePyMOLScript(result);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = `${result.name.replace(/[^a-zA-Z0-9]/g, '_')}_pymol_script.pml`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

/**
 * Generate PyMOL command line for local execution
 * Creates a command that user can copy and run
 */
export const getPyMOLCommand = (result: AnalysisResult): string => {
    const pdbId = result.pdbId || '1hbb';
    return `pymol -d "fetch ${pdbId}; show cartoon; color spectrum; bg white; zoom;"`;
};

/**
 * Generate a PyMOL movie script for animation
 */
export const generatePyMOLMovieScript = (result: AnalysisResult): string => {
    const pdbId = result.pdbId || '1hbb';

    return `# PyMOL Movie Script for ${result.name}
# Creates a rotating 360-degree view of the structure

fetch ${pdbId}, async=0

# Setup
cmd.show('cartoon')
cmd.color('teal')
cmd.bg_color('white')
cmd.set('ray_trace_frames', 1)
cmd.set('cache_frames', 1)

# Movie: 360 degree rotation over 180 frames (6 seconds at 30fps)
cmd.mset('1 x180')

for i in range(1, 181):
    cmd.frame(i)
    cmd.rotate('y', 2)

# Save movie (uncomment to use)
# cmd.mpng('${result.name.replace(/[^a-zA-Z0-9]/g, '_')}_rotation', first=1, last=180)

print("Movie script ready. Run 'mplay' to preview.")
`;
};

/**
 * Generate a PyMOL session with advanced representations
 */
export const generateAdvancedPyMOLScript = (result: AnalysisResult): string => {
    const pdbId = result.pdbId || '1hbb';

    return `# Advanced PyMOL Visualization for ${result.name}
# BioSeq Portal Analysis Export
# Includes: Surface, electrostatics, and ligand interactions

# Load structure
fetch ${pdbId}, async=0

# ========== BASIC SETUP ==========
cmd.set('bg_rgb', [1, 1, 1])  # White background
cmd.set('orthoscopic', 1)      # Orthoscopic view
cmd.set('depth_cue', 0)        # Disable depth fog

# ========== REPRESENTATIONS ==========
# Main protein structure
cmd.show('cartoon', 'polymer')
cmd.color('cyan', 'polymer')

# Secondary structure coloring
cmd.color('red', 'ss h')       # Helices in red
cmd.color('yellow', 'ss s')    # Sheets in yellow
cmd.color('green', 'ss l+\"\"') # Loops in green

# Side chains
cmd.show('sticks', 'sidechain')
cmd.set('stick_radius', 0.15)

# Surface representation
cmd.show('surface', 'polymer')
cmd.set('surface_color', 'white')
cmd.set('transparency', 0.7)

# ========== HETERO ATOMS (LIGANDS/COFACTORS) ==========
cmd.show('spheres', 'hetero and not water')
cmd.show('sticks', 'hetero and not water')
cmd.color('magenta', 'hetero and not water')
cmd.set('sphere_scale', 0.3, 'hetero and not water')

# ========== MEASUREMENTS ==========
# Label binding sites if hetero atoms exist
if cmd.count_atoms('hetero and not water') > 0:
    cmd.distance('ligand_contact', 'polymer within 5 of (hetero and not water)', 'hetero and not water')
    cmd.set('dash_color', 'red', 'ligand_contact')
    cmd.set('dash_width', 3)

# ========== FINAL VIEW ==========
cmd.zoom('visible', 5)
cmd.orient()

# Save session (uncomment to save)
# cmd.save('${result.name.replace(/[^a-zA-Z0-9]/g, '_')}_session.pse')

print("Advanced PyMOL visualization loaded for ${result.name}")
`;
};

export default {
    generatePyMOLScript,
    generatePyMOLSession,
    generatePyMOLColorScript,
    downloadPyMOLScript,
    getPyMOLCommand,
    generatePyMOLMovieScript,
    generateAdvancedPyMOLScript
};
